In [1]:
import numpy as np
import pandas as pd
from sklearn import datasets
iris = datasets.load_iris()
iris_data = iris.data
iris_labels = iris.target

In [2]:
data1 = pd.DataFrame(data= np.c_[iris_data, iris_labels],
                     columns= iris['feature_names'] + ['target'])
data1.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

In [3]:
# menentukan training data dan testing data, gunakan random untuk indexing
np.random.seed(10)
# index data
indices = np.random.permutation(len(iris_data))
#print(indices)
# jumlah data yang di ambil
n_training_samples = 40
learnset_data = iris_data[indices[:-n_training_samples]]
learnset_labels = iris_labels[indices[:-n_training_samples]]
testset_data = iris_data[indices[-n_training_samples:]]
testset_labels = iris_labels[indices[-n_training_samples:]]
print(learnset_data, learnset_labels)
print(testset_data, testset_labels)

(array([[6.3, 2.3, 4.4, 1.3],
       [6.4, 2.7, 5.3, 1.9],
       [5.4, 3.7, 1.5, 0.2],
       [6.1, 3. , 4.6, 1.4],
       [5. , 3.3, 1.4, 0.2],
       [5. , 2. , 3.5, 1. ],
       [6.3, 2.5, 4.9, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [5.1, 3.4, 1.5, 0.2],
       [5.7, 2.8, 4.5, 1.3],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 5.1, 1.9],
       [5.5, 2.3, 4. , 1.3],
       [4.9, 3. , 1.4, 0.2],
       [5.1, 3.8, 1.5, 0.3],
       [6.8, 3. , 5.5, 2.1],
       [6. , 3.4, 4.5, 1.6],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [5. , 3.2, 1.2, 0.2],
       [7.1, 3. , 5.9, 2.1],
       [6.4, 2.8, 5.6, 2.2],
       [6.2, 2.8, 4.8, 1.8],
       [4.8, 3.4, 1.9, 0.2],
       [5.9, 3. , 4.2, 1.5],
       [4.7, 3.2, 1.3, 0.2],
       [5.7, 3. , 4.2, 1.2],
       [5.5, 2.6, 4.4, 1.2],
       [6.8, 2.8, 4.8, 1.4],
       [7.7, 3.8, 6.7, 2.2],
       [6.6, 2.9, 4.6, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [7.2, 3. , 5.8, 1.6],
       [5.8, 2.8, 5.1, 2.4],
       [6.3, 

In [4]:
# mencari jarak/similarity dengan euclidean
def distance(instance1, instance2):
    # buat jaga2 kalo instans nya adalah list atau tuple
    instance1 = np.array(instance1) 
    instance2 = np.array(instance2)
    
    return np.linalg.norm(instance1 - instance2)
print(distance([5.7, 3.8, 1.7, 0.3], [5,2.3,3.3,1]))
print(distance(learnset_data[87], learnset_data[9]))

2.406241883103193
0.412310562561766


In [5]:
def get_neighbors(training_set, 
                  labels, 
                  test_instance, 
                  k, 
                  distance=distance):
    distances = []
    for index in range(len(training_set)):
        dist = distance(test_instance, training_set[index])
        distances.append((training_set[index], dist, labels[index]))
    distances.sort(key=lambda x: x[1])
    neighbors = distances[:k]
    return neighbors

In [6]:
# jumlah testing data yg diambil hanya 3, dan melihat tetangganya siapa saja
for i in range(40):
    neighbors = get_neighbors(learnset_data, 
                              learnset_labels, 
                              testset_data[i], 
                              3, # jumlah neighbour yang bisa diubah
                              distance=distance)
    print(i, 
          "data testing=", testset_data[i], 
          "label data=",testset_labels[i],
          "Neighbours=" ,neighbors)

(0, 'data testing=', array([5.7, 3.8, 1.7, 0.3]), 'label data=', 0, 'Neighbours=', [(array([5.4, 3.9, 1.7, 0.4]), 0.33166247903553986, 0), (array([5.4, 3.7, 1.5, 0.2]), 0.3872983346207414, 0), (array([5.3, 3.7, 1.5, 0.2]), 0.46904157598234314, 0)])
(1, 'data testing=', array([5.2, 3.5, 1.5, 0.2]), 'label data=', 0, 'Neighbours=', [(array([5.2, 3.4, 1.4, 0.2]), 0.14142135623730964, 0), (array([5.1, 3.4, 1.5, 0.2]), 0.14142135623730995, 0), (array([5.1, 3.5, 1.4, 0.3]), 0.17320508075688806, 0)])
(2, 'data testing=', array([5.5, 3.5, 1.3, 0.2]), 'label data=', 0, 'Neighbours=', [(array([5.4, 3.7, 1.5, 0.2]), 0.3, 0), (array([5.2, 3.4, 1.4, 0.2]), 0.33166247903553986, 0), (array([5.3, 3.7, 1.5, 0.2]), 0.3464101615137756, 0)])
(3, 'data testing=', array([4.9, 2.4, 3.3, 1. ]), 'label data=', 1, 'Neighbours=', [(array([5. , 2.3, 3.3, 1. ]), 0.1414213562373093, 1), (array([5.1, 2.5, 3. , 1.1]), 0.38729833462074126, 1), (array([5. , 2. , 3.5, 1. ]), 0.4582575694955839, 1)])
(4, 'data testing=',

In [7]:
#mencari kelas yg paling banyak muncul diantara neighbour
from collections import Counter
def claspred(neighbors):
    class_counter = Counter()
    for neighbor in neighbors:
        class_counter[neighbor[2]] += 1
    return class_counter.most_common(1)[0][0]

In [8]:
#tampilkan data testing, class prediksi dan kelas asli
#for i in range(n_training_samples):
#    neighbors = get_neighbors(learnset_data, 
#                              learnset_labels, 
#                              testset_data[i], 
#                              10, 
#                              distance=distance)
#    print("index: ", i, 
#          ", class prediction: ", claspred(neighbors), 
#          ", label: ", testset_labels[i], 
#          ", data: ", testset_data[i])

In [9]:
numb = []
new_numb = 0
for i in range(n_training_samples):
    neighbors = get_neighbors(learnset_data, 
                              learnset_labels, 
                              testset_data[i], 
                              3, 
                              distance=distance)
    numb.append(claspred(neighbors))

In [10]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(testset_labels, numb))
print(classification_report(testset_labels, numb))

[[15  0  0]
 [ 0 12  0]
 [ 0  1 12]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        15
          1       0.92      1.00      0.96        12
          2       1.00      0.92      0.96        13

avg / total       0.98      0.97      0.97        40

